### ISSUE TITLE
nobs

### ISSUE THREAD

**Issue by reetakankaanpaa** [SachaEpskamp/psychonetrics#14]
Hi, my question relates to the meaning of nobs. If it refers to number of observations in the analysis, it seems terribly wrong and I don't dare to continue with the analysis before I know what's wrong. I have a sample size over 3000, and in any model, nobs: 230. What could be the reason?

**Comment by SachaEpskamp** [comment]
This refers to the sample size!

**Comment by reetakankaanpaa** [comment]
Thank you for your response. Would you have any idea why the model doesn't use the full sample size? There are no missing values, I've checked the data using different descriptives and the sample is over 3000. Still, which ever psychonetrics model I run, the sample is 230.
