### ISSUE TITLE
Setting up ml_gvar

### ISSUE THREAD

**Issue by bbailey1451** [SachaEpskamp/psychonetrics#17]
Hello,

I am trying to use psychonetrics for the first time to analyze N >1 panel data. The data are set up in long format consistent with the format I have used with the mlVAR package. There are 1683 total observations and 15 variables. Data have been imputed such that there are no missing values. 

![image](https://user-images.githubusercontent.com/113918432/191782665-219f2505-1ee4-464f-aa12-bbd53d87a98f.png)

vars <- c("BDI1", "BDI2", "BDI5", "BDI9", "BDI11", "BDI13","BDI16", "BDI17","BDI18", "BDI19", "anhedonia", "tired", "negselfview4")
panelmodel <- ml_gvar(df, vars = vars, idvar = "patno", beepvar = "session", standardize = "z")

When running the model above, I encounter the following error message:

Error in is.data.frame(x) : 
  'list' object cannot be coerced to type 'double'
In addition: Warning message:
In mean.default(data[, vars[v]], na.rm = TRUE) :
  argument is not numeric or logical: returning NA

I have not yet been able to resolve this issue. I appreciate any help to get me going with this analysis!

Best,
Brooklynn

**Comment by SachaEpskamp** [comment]
Hi Brooklynn,

Are you sure the variables are all encoded as numeric? And perhaps it helps if you transform the data into a data frame with `as.data.frame`?

Best,
Sacha

**Comment by bbailey1451** [comment]
Hi Sacha,

Thanks for the response! All variables are confirmed to be numeric. I had set the data up as a data frame before but encountered a different error. Turns out removing and re-installing the Rcpp package resolved it, while just updating Rcpp was insufficient.

I am looking forward to trying out panel VAR analyses with this new package! Thanks again!

Brooklynn
