### ISSUE TITLE
Pruning ml_gvar

### ISSUE THREAD

**Issue by bbailey1451** [SachaEpskamp/psychonetrics#18]
Hello,
I wanted to report an issue which emerged when pruning a psychonetrics model estimated using the ml_gvar function. As seen below, the estimated model was pruned at alpha of .05. The temporal and contemporaneous networks were successfully pruned. Meanwhile, a fully saturated between subject network was retained after pruning. 
Best,
Brooklynn 

# Run model 
model <- ml_gvar(data = data, vars = vars, idvar = "patno", beepvar = "session", contemporaneous = "ggm", between = "chol", standardize = "z") %>% runmodel

# Remove non-significant edges
model05 <- model %>% prune(alpha = 0.05)

# Extract temporal, contemporaneous, and between subject effects
model_tmatrix  <- getmatrix(model05, "PDC")
model_cmatrix <- getmatrix(model05, "omega_zeta_within") 
model_bmatrix <- getmatrix(model05, "omega_zeta_between")

# Plot 
model_tnet <- qgraph(model_tmatrix, labels= varlabels, layout= "spring")
model_cnet <- qgraph(model_cmatrix, labels= varlabels, layout= "spring")
model_bnet <- qgraph(model_bmatrix, labels= varlabels, layout= "spring")

**Comment by SachaEpskamp** [comment]
Hi! This is correct. The `prune` function does not prune the `lowerTri` matrices from Cholesky decompositions by default, nor do you want to. You model the between subject effects with a Cholesky with `between = "chol"`. I recommend this if `between = "ggm"` gives weird and seemingly unstable results. If you use `between = "chol"`, I would only substantively interpret the temporal and contemporaneous networks.
