### ISSUE TITLE
CFA on sumstats yields errors

### ISSUE THREAD

**Issue by KJKan** [SachaEpskamp/psychonetrics#2]
Running CFA on summary statistics does not seem to work.

Even when I run the example made available at https://github.com/SachaEpskamp/SEM-code-examples/blob/master/SEM_fit_examples/psychonetrics_sumstat.R this results in the following error(s):

Model estimation failed. Perturbing start values.
Error in thresholds[[g]] : subscript out of bounds
Model estimation failed and 'maxtry' reached. Returning error.

**Comment by SachaEpskamp** [comment]
Fixed now in devel. Thanks for reporting!

Note that devel is quite unstable now as I am switching some internal things to be compatible with C++.
