### ISSUE TITLE
“ucminf” is not valid for @‘optim’ 

### ISSUE THREAD

**Issue by tasospsy** [SachaEpskamp/psychonetrics#21]
Dear Sacha, 
I used to use the 'ucminf' optimizer in `lvm` function.  Lately, I rerun some code but I had the following error when I pass the model to the `runmodel` function. The error is not shown when the default optimizer is used.
```
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “ucminf” is not valid for @‘optim’ in an object of class “psychonetrics”; is(value, "list") is not TRUE
```
Any ideas? Have anything changed in the recent versions? 
Best, Tasos. 

### Sample code:
`sample_cov <- matrix(c(1, 0.49, 0.45,
                        0.49, 1, 0.48, 
                        0.45, 0.48, 1), 
                      nrow = 3, ncol =3, byrow=TRUE)
dimnames(sample_cov) <- list(c('A','B','C'), c('A','B','C'))
obsvars <- rownames(sample_cov)

lambda <- matrix(c(1, 1, 1),nrow = 3,ncol = 1, byrow = TRUE)
nobs = 2000
testmod <- lvm(lambda = lambda,
               sigma_zeta = "empty",
    covs = nobs-1 /
      nobs * sample_cov,
    nobs = nobs,
    identification = "variance",
    optimizer = 'ucminf') %>% runmodel`

### Session info
`─ Session info ──────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       macOS Ventura 13.0.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Oslo
 date     2023-09-05
 rstudio  2023.06.1+524 Mountain Hydrangea (desktop)
 pandoc   3.1.5 @ /opt/homebrew/bin/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────
 package       * version     date (UTC) lib source
 abind           1.4-5       2016-07-21 [1] CRAN (R 4.2.0)
 backports       1.4.1       2021-12-13 [1] CRAN (R 4.2.0)
 base64enc       0.1-3       2015-07-28 [1] CRAN (R 4.2.0)
 boot            1.3-28.1    2022-11-22 [1] CRAN (R 4.2.0)
 cachem          1.0.8       2023-05-01 [1] CRAN (R 4.2.0)
 callr           3.7.3       2022-11-02 [1] CRAN (R 4.2.0)
 checkmate       2.2.0       2023-04-27 [1] CRAN (R 4.2.0)
 cli             3.6.1       2023-03-23 [1] CRAN (R 4.2.0)
 cluster         2.1.4       2022-08-22 [1] CRAN (R 4.2.2)
 codetools       0.2-19      2023-02-01 [1] CRAN (R 4.2.0)
 colorspace      2.1-0       2023-01-23 [1] CRAN (R 4.2.0)
 combinat        0.0-8       2012-10-29 [1] CRAN (R 4.2.0)
 corpcor         1.6.10      2021-09-16 [1] CRAN (R 4.2.0)
 crayon          1.5.2       2022-09-29 [1] CRAN (R 4.2.0)
 curl            5.0.2       2023-08-14 [1] CRAN (R 4.2.0)
 data.table      1.14.8      2023-02-17 [1] CRAN (R 4.2.0)
 desc            1.4.2       2022-09-08 [1] CRAN (R 4.2.0)
 devtools      * 2.4.5       2022-10-11 [1] CRAN (R 4.2.0)
 digest          0.6.33      2023-07-07 [1] CRAN (R 4.2.0)
 dplyr         * 1.1.2       2023-04-20 [1] CRAN (R 4.2.0)
 ellipsis        0.3.2       2021-04-29 [1] CRAN (R 4.2.0)
 evaluate        0.21        2023-05-05 [1] CRAN (R 4.2.0)
 fansi           1.0.4       2023-01-22 [1] CRAN (R 4.2.0)
 fastmap         1.1.1       2023-02-24 [1] CRAN (R 4.2.0)
 fdrtool         1.2.17      2021-11-13 [1] CRAN (R 4.2.0)
 forcats       * 1.0.0       2023-01-29 [1] CRAN (R 4.2.0)
 foreach         1.5.2       2022-02-02 [1] CRAN (R 4.2.0)
 foreign         0.8-84      2022-12-06 [1] CRAN (R 4.2.0)
 Formula         1.2-5       2023-02-24 [1] CRAN (R 4.2.0)
 fs              1.6.3       2023-07-20 [1] CRAN (R 4.2.0)
 GA              3.2.3       2022-10-18 [1] CRAN (R 4.2.0)
 generics        0.1.3       2022-07-05 [1] CRAN (R 4.2.0)
 ggplot2       * 3.4.3       2023-08-14 [1] CRAN (R 4.2.0)
 glasso          1.11        2019-10-01 [1] CRAN (R 4.2.0)
 glue            1.6.2       2022-02-24 [1] CRAN (R 4.2.0)
 GPArotation   * 2023.3-1    2023-03-21 [1] CRAN (R 4.2.0)
 gridExtra       2.3         2017-09-09 [1] CRAN (R 4.2.0)
 gtable          0.3.3       2023-03-21 [1] CRAN (R 4.2.0)
 gtools          3.9.4       2022-11-27 [1] CRAN (R 4.2.0)
 Hmisc           5.1-0       2023-05-08 [1] CRAN (R 4.2.0)
 hms             1.1.3       2023-03-21 [1] CRAN (R 4.2.0)
 htmlTable       2.4.1       2022-07-07 [1] CRAN (R 4.2.0)
 htmltools       0.5.6       2023-08-10 [1] CRAN (R 4.2.0)
 htmlwidgets     1.6.2       2023-03-17 [1] CRAN (R 4.2.0)
 httpuv          1.6.11      2023-05-11 [1] CRAN (R 4.2.0)
 igraph          1.5.1       2023-08-10 [1] CRAN (R 4.2.0)
 IsingSampler    0.2.1       2020-01-25 [1] CRAN (R 4.2.0)
 iterators       1.0.14      2022-02-05 [1] CRAN (R 4.2.0)
 jpeg            0.1-10      2022-11-29 [1] CRAN (R 4.2.0)
 knitr           1.43        2023-05-25 [1] CRAN (R 4.2.0)
 later           1.3.1       2023-05-02 [1] CRAN (R 4.2.0)
 lattice         0.21-8      2023-04-05 [1] CRAN (R 4.2.0)
 lavaan          0.6-16      2023-07-19 [1] CRAN (R 4.2.0)
 lifecycle       1.0.3       2022-10-07 [1] CRAN (R 4.2.0)
 lme4            1.1-34      2023-07-04 [1] CRAN (R 4.2.0)
 lubridate     * 1.9.2       2023-02-10 [1] CRAN (R 4.2.0)
 magrittr        2.0.3       2022-03-30 [1] CRAN (R 4.2.0)
 MASS          * 7.3-60      2023-05-04 [1] CRAN (R 4.2.0)
 Matrix          1.5-1       2022-09-13 [1] CRAN (R 4.2.2)
 memoise         2.0.1       2021-11-26 [1] CRAN (R 4.2.0)
 mgcv            1.9-0       2023-07-11 [1] CRAN (R 4.2.0)
 mime            0.12        2021-09-28 [1] CRAN (R 4.2.0)
 miniUI          0.1.1.1     2018-05-18 [1] CRAN (R 4.2.0)
 minqa           1.2.5       2022-10-19 [1] CRAN (R 4.2.0)
 mnormt          2.1.1       2022-09-26 [1] CRAN (R 4.2.0)
 munsell         0.5.0       2018-06-12 [1] CRAN (R 4.2.0)
 nlme            3.1-163     2023-08-09 [1] CRAN (R 4.2.0)
 nloptr          2.0.3       2022-05-26 [1] CRAN (R 4.2.0)
 nnet            7.3-19      2023-05-03 [1] CRAN (R 4.2.0)
 numDeriv        2016.8-1.1  2019-06-06 [1] CRAN (R 4.2.0)
 optextras       2019-12.4   2019-12-20 [1] CRAN (R 4.2.0)
 optimr        * 2019-12.16  2019-12-17 [1] CRAN (R 4.2.0)
 optimx          2023-8.13   2023-08-14 [1] CRAN (R 4.2.0)
 patchwork     * 1.1.3       2023-08-14 [1] CRAN (R 4.2.0)
 pbapply         1.7-2       2023-06-27 [1] CRAN (R 4.2.0)
 pbivnorm        0.6.0       2015-01-23 [1] CRAN (R 4.2.0)
 pillar          1.9.0       2023-03-22 [1] CRAN (R 4.2.0)
 pkgbuild        1.4.2       2023-06-26 [1] CRAN (R 4.2.0)
 pkgconfig       2.0.3       2019-09-22 [1] CRAN (R 4.2.0)
 pkgload         1.3.2.1     2023-07-08 [1] CRAN (R 4.2.0)
 plyr            1.8.8       2022-11-11 [1] CRAN (R 4.2.0)
 png             0.1-8       2022-11-29 [1] CRAN (R 4.2.0)
 pracma          2.4.2       2022-09-22 [1] CRAN (R 4.2.0)
 prettyunits     1.1.1       2020-01-24 [1] CRAN (R 4.2.0)
 processx        3.8.2       2023-06-30 [1] CRAN (R 4.2.0)
 profvis         0.3.8       2023-05-02 [1] CRAN (R 4.2.0)
 promises        1.2.1       2023-08-10 [1] CRAN (R 4.2.0)
 ps              1.7.5       2023-04-18 [1] CRAN (R 4.2.0)
 psych           2.3.6       2023-06-21 [1] CRAN (R 4.2.0)
 psychonetrics * 0.11        2023-06-05 [1] CRAN (R 4.2.0)
 purrr         * 1.0.2       2023-08-10 [1] CRAN (R 4.2.0)
 qgraph        * 1.9.5       2023-05-16 [1] CRAN (R 4.2.0)
 quadprog        1.5-8       2019-11-20 [1] CRAN (R 4.2.0)
 R6              2.5.1       2021-08-19 [1] CRAN (R 4.2.0)
 Rcgmin          2022-4.30   2022-05-11 [1] CRAN (R 4.2.0)
 Rcpp            1.0.11      2023-07-06 [1] CRAN (R 4.2.0)
 readr         * 2.1.4       2023-02-10 [1] CRAN (R 4.2.0)
 remotes         2.4.2.1     2023-07-18 [1] CRAN (R 4.2.0)
 reshape2        1.4.4       2020-04-09 [1] CRAN (R 4.2.0)
 rlang           1.1.1       2023-04-28 [1] CRAN (R 4.2.0)
 rmarkdown       2.24        2023-08-14 [1] CRAN (R 4.2.0)
 rpart           4.1.19      2022-10-21 [1] CRAN (R 4.2.2)
 rprojroot       2.0.3       2022-04-02 [1] CRAN (R 4.2.0)
 rstudioapi      0.15.0      2023-07-07 [1] CRAN (R 4.2.0)
 Rvmmin          2018-4.17.1 2021-04-18 [1] CRAN (R 4.2.0)
 scales          1.2.1       2022-08-20 [1] CRAN (R 4.2.0)
 sessioninfo     1.2.2       2021-12-06 [1] CRAN (R 4.2.0)
 setRNG          2022.4-1    2022-04-03 [1] CRAN (R 4.2.0)
 shiny           1.7.5       2023-08-12 [1] CRAN (R 4.2.0)
 stringi         1.7.12      2023-01-11 [1] CRAN (R 4.2.0)
 stringr       * 1.5.0       2022-12-02 [1] CRAN (R 4.2.0)
 tibble        * 3.2.1       2023-03-20 [1] CRAN (R 4.2.0)
 tidyr         * 1.3.0       2023-01-24 [1] CRAN (R 4.2.0)
 tidyselect      1.2.0       2022-10-10 [1] CRAN (R 4.2.0)
 tidyverse     * 2.0.0       2023-02-22 [1] CRAN (R 4.2.0)
 timechange      0.2.0       2023-01-11 [1] CRAN (R 4.2.0)
 tzdb            0.4.0       2023-05-12 [1] CRAN (R 4.2.0)
 ucminf        * 1.2.0       2023-05-29 [1] CRAN (R 4.2.0)
 urlchecker      1.0.1       2021-11-30 [1] CRAN (R 4.2.0)
 usethis       * 2.2.2       2023-07-06 [1] CRAN (R 4.2.0)
 utf8            1.2.3       2023-01-31 [1] CRAN (R 4.2.0)
 VCA             1.4.5       2022-09-07 [1] CRAN (R 4.2.0)
 vctrs           0.6.3       2023-06-14 [1] CRAN (R 4.2.0)
 withr           2.5.0       2022-03-03 [1] CRAN (R 4.2.0)
 xfun            0.40        2023-08-09 [1] CRAN (R 4.2.0)
 xtable          1.8-4       2019-04-21 [1] CRAN (R 4.2.0)`

**Comment by SachaEpskamp** [comment]
Thanks for reporting. The ucminf optimizer seems to be bugged right now. I don't recommend changing the default optimizer however. If you have convergence issues you might want to standardize the data with standardize = "z" if you use rawdata or cov2cor(..) if you use a covariance matrix as input. 

Note that your example code has a severe problem in the line `covs = nobs-1 / nobs * sample_cov`. I think you meant `covs = (nobs-1) / nobs * sample_cov` there instead? Adjusting the covariance matrix is not needed, you should instead use the `covtype` argument to indicate if the covariances are maximum likelihood (ML; n as denominator) or unbiased (UB; n-1 as denominator). You now supply the following covariance matrixs:
```
         A        B        C
A 1999.999 2000.000 2000.000
B 2000.000 1999.999 2000.000
C 2000.000 2000.000 1999.999
```
Which is not positive definite and will lead to issues. This runs ok:
```
library("psychonetrics")
library("dplyr")

sample_cov <- matrix(c(1, 0.49, 0.45,
                        0.49, 1, 0.48,
                        0.45, 0.48, 1),
                      nrow = 3, ncol =3, byrow=TRUE)
dimnames(sample_cov) <- list(c('A','B','C'), c('A','B','C'))
obsvars <- rownames(sample_cov)

lambda <- matrix(c(1, 1, 1),nrow = 3,ncol = 1, byrow = TRUE)
nobs = 2000
testmod <- lvm(lambda = lambda,
               sigma_zeta = "empty",
               covs = sample_cov,
               covtype = "UB",
               nobs = nobs,
               identification = "variance") %>% runmodel
```
