### ISSUE TITLE
model <- lvm(... equal=c("lambda")) gives different results to ... lvm(...) %>% groupequal("lambda")

### ISSUE THREAD

**Issue by tomvojtisek** [SachaEpskamp/psychonetrics#29]
reflective <- lvm(covs = covlist, nobs = nobslist,
                  lambda = lambda.profile, sigma_zeta = "full",
                  sigma_epsilon = 'empty',
                  latents = dimensions ) %>% groupequal("lambda") %>% groupequal("beta")

reflective.alt <- lvm(covs = covlist, nobs = nobslist,
                      lambda = lambda.profile, sigma_zeta = "full",
                      sigma_epsilon = 'empty',
                      latents = dimensions, equal = c("lambda","beta"))

reflective <- try({runmodel(reflective)},silent=TRUE)
reflective.alt <- try({runmodel(reflective.alt)},silent=TRUE)
compare(reflective,reflective.alt)

yields different models, indicating that the group invariance restriction on lambda and beta does not work the same for the argument equal = .. vs groupequal(..)

specifically, use of equal =c(..) does not in fact estimate equal parameters accross the groups.

**Comment by SachaEpskamp** [comment]
Thank you for reporting. Indeed the equal argument seems not to work now for lambda and beta. I'll fix this in a future version, but I recommend to use the first approach as it will lead to better starting values.

**Comment by SachaEpskamp** [comment]
Fixed now in devel version.
