### ISSUE TITLE
multigroup residual network model estimation with group equality constraints yields different omega_epsilon estimates for groups when stepup(mi="mi_equal") is used. 

### ISSUE THREAD

**Issue by tomvojtisek** [SachaEpskamp/psychonetrics#30]
Is this intended? I would expect that for a multigroup model with equality constraints, the modelsearch with group-equality-restrained modification indices should result in the addition of equal parameters across groups.

**Comment by SachaEpskamp** [comment]
Yes this function is not yet build to add parameters that are equality constrained.

Best,
Sacha
