### ISSUE TITLE
Parametric modulators of edge strength

### ISSUE THREAD

**Issue by ozika** [SachaEpskamp/psychonetrics#37]
Hi, 

First, thanks for making the package with all its accessories accessible!  

I had a perhaps more of a theoretical question. I am estimating a small network of 6 variables across 20 sessions. Whilst I am interested in the network itself, I am also interested to see how individual differences (e.g. income) might modulate edge strength (what I would investigate using an interaction in a glm). 

So far, I wasn't able to find an option to do this. The closest way that I found is to estimate individual networks, extract the edges and then correlate them with the continuous measure. This isn't working very well because many individual edges get regularized to 0.  

Additionally, it feels like including the interaction directly in the model would be the way to go.  

If you have any suggestion I'd be interested to hear them! 

Thanks!

**Comment by SachaEpskamp** [comment]
Hi! I am afraid that this type of modeling is not possible in the package. As far as I know, it is only possible in an accessible way using MPlus, but there you do not obtain partial correlation networks.
