### ISSUE TITLE
Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by Virgg** [SachaEpskamp/psychonetrics#38]
Hi,
I currently have this issue,
remotes::install_github("sachaepskamp/psychonetrics")
Downloading GitHub repo sachaepskamp/psychonetrics@HEAD
Error: Failed to install 'psychonetrics' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

and

C:\RBuildTools\4.3\mingw64\bin  is empty

Thank you.

**Comment by SachaEpskamp** [comment]
You can just install the CRAN version with `install.packages("psychonetrics"), it is the same as the current Github version!
