### ISSUE TITLE
Error in zero[k, 1] : subscript out of bounds

### ISSUE THREAD

**Issue by Deleetdk** [SachaEpskamp/psychonetrics#4]
Following your example but with my code, I get a runtime error when attempting to `prune()`:

```
library("psychonetrics")
library("dplyr")

model <- ggm(SPI_imputed, vars = SPI_imputed[2:52] %>% names(), omega = "full")
model <- model %>% runmodel()
model

#prune to sparse
#these give runtime errors
prunedmodel_1 <- model %>% runmodel() %>% stepup() %>% prune()
prunedmodel_2 <- model %>% runmodel() %>% prune() %>% stepup()

#just one of them
prunedmodel_3 <- model %>% runmodel() %>% prune()
prunedmodel_4 <- model %>% runmodel() %>% stepup()
```

The error happens with the `prune()` call, not the `stepup()` call.

```
> prunedmodel_3 <- model %>% runmodel() %>% prune()
Error in zero[k, 1] : subscript out of bounds
```

I attach my data. It's the Social Progress Index dataset from here (https://www.socialprogress.org/index/global/methodology), but I imputed the missing data for countries with at most 30% missing data (with VIM's `irmi()`). It's a dataset of 51 indicators of country well-being. Some countries are so bad they don't have proper data, so that's why the imputation is needed, but we still end up with some 20% of the cases with too little data, so we end with 176 cases.

[SPI_imputed.xlsx](https://github.com/SachaEpskamp/psychonetrics/files/4601054/SPI_imputed.xlsx)

Versions:
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 19.3
- Packages, all latest CRAN, psychonetrics_0.7.1

**Comment by SachaEpskamp** [comment]
Hi,

Looking at this, there are many variables and not that many observations. This may be too complex for psychonetrics to handle. I think it would be better to use LASSO regularization instead here perhaps.
