### ISSUE TITLE
Regarding to NetworkComparisonTest issues

### ISSUE THREAD

**Issue by wondang** [SachaEpskamp/psychonetrics#5]
Dear Sacha Epsakamp,

I would appreciate your view on Network ComparisonTest using NCT. In particular, I am running the code with my datasets, and the results came out as NA as follow:

nct_results <- NCT(data.hf.p, data.hf.g, it=1000, weighted=TRUE, progressbar = TRUE, test.edges=TRUE, edges='all')

nct_results$glstrinv.sep # connectivity values: NA NA

nct_results$glstrinv.real # difference in connectivity: NA

nct_results$glstrinv.pval # global strength invariance: NA

I am a bit confused about this issue. I am using cross-sectional data, with n1=9000 and n2=5000. The datasets including ordinal, binary, and continuous variables.

Thank you once again for your time and consideration.

**Comment by SachaEpskamp** [comment]
Please post this on the Github page of the [NetworkComparisonTest](https://github.com/cvborkulo/NetworkComparisonTest) package.
