### ISSUE TITLE
The latent variables and observed variables

### ISSUE THREAD

**Issue by Shunsenhuang-123** [SachaEpskamp/psychonetrics#8]
Dear, Epskamp:
    As this package fails to deal with variables exceeding the number of 30, but what can I do if I exactly have 100 observed variables (10 latent variables). Can I calculate the mean score of each latent variables, and use the 10 latent variables as observed variables in the analysis?  I am not very sure whether this is acceptable in this package.

Thank you!

**Comment by SachaEpskamp** [comment]
Sometimes indeed the best way is to include scale scores. It is not ideal, but if you don't have enough data to model the latent variables or if the number of variables is too much there might not be another option.
